#!/bin/bash

DOCKER_NAME=servicedesk
docker container run \
	--name ${DOCKER_NAME} \
	--hostname ${DOCKER_NAME}  \
	--detach \
	--rm \
	--network bridge \
	--mount type=bind,source=$(pwd)/www,destination=/var/www/localhost/htdocs/ \
	--mount type=bind,source=$(pwd)/log,destination=/var/www/logs/ \
	--mount type=bind,source=$(pwd)/httpd_conf/httpd.conf,destination=/etc/apache2/httpd.conf \
	--mount type=bind,source=$(pwd)/php_ini/php.ini,destination=/etc/php81/php.ini \
	--mount type=bind,source=$(pwd)/glpi_config,destination=/etc/glpi \
	--mount type=bind,source=$(pwd)/glpi_data,destination=/var/lib/glpi \
	--mount type=bind,source=$(pwd)/log/glpi_logs,destination=/var/log/glpi \
	--mount type=bind,source=$(pwd)/downstream.php,destination=/var/www/localhost/htdocs/inc/downstream.php \
	--init \
	routerology/glpi

