#!/bin/bash
DOCKER_NAME=glpi
docker container run -d --rm --name ${DOCKER_NAME} --hostname ${DOCKER_NAME} --network br0\
	-v /var/docks/glpi/site:/var/www/ \
	-v /var/docks/glpi/php.ini:/usr/local/etc/php/php.ini \
	-e TZ=Europe/Bucharest \
	--init \
	--log-driver=syslog \
  	--log-opt syslog-address=udp://172.16.100.1:514 \
  	--log-opt tag=${DOCKER_NAME} \
  	--log-opt syslog-format=rfc5424 \
	glpi_img
#	glpi_img /root/wrapper_script.sh

#-v /var/docks/intranet/000-default.conf:/etc/apache2/sites-available/000-default.conf \
