#!/bin/bash
DOCKER_NAME=mariadb
docker container run \
	--detach \
	--name ${DOCKER_NAME} --hostname ${DOCKER_NAME} \
	--network bridge \
	-e MARIADB_ROOT_PASSWORD=pass123 \
	-e TZ=Europe/Bucharest \
	mariadb:latest
#-v $(pwd)/data:/var/lib/mysql/ \
#-v $(pwd)/conf:/etc/mysql/conf.d \
#	--init \
#	--log-driver=syslog \
#  	--log-opt syslog-address=udp://172.16.100.1:514 \
# 	--log-opt tag=${DOCKER_NAME} \
#	--log-opt syslog-format=rfc5424 \


#
#	MARIADB_ROOT_HOST / MYSQL_ROOT_HOST

# This is the hostname part of the root user created. 
# By default this is %, however it can be set to any default MariaDB allowed hostname component. 
# Setting this to localhost will prevent any root user being accessible except via the unix socket.
#
# MARIADB_DATABASE / MYSQL_DATABASE
# MARIADB_USER / MYSQL_USER, MARIADB_PASSWORD / MYSQL_PASSWORD
